### ISSUE TITLE
Support platforms other than Windows

### ISSUE THREAD

**Issue by helluvamatt** [helluvamatt/TouchRemote#9]
The application is currently written targeting .NET Framework 4.6.1 using Windows Presentation Foundation. This platform only supports Windows, and there are no plans to include WPF in cross-platform versions of .NET Standard (.NET Core or Mono). In order to support platforms other than Windows, an almost complete rewrite of the UI will be required. Before that, we must ensure that other components will work under the targeted .NET Standard.

#### Required core components (web server, etc...)

For starters, the required web server and real-time communications components (Suave, Nancy, and SignalR) will need to be supported going forward. (For .NET Core, a new version of SignalR is being developed which will be released with ASP.NET Core 2.1 in about Q2 2018). Note that .NET Standard (Mono under Unix, .NET Framework under Windows) is also an option, assuming the required components support targeting the standard. A way around this would be to build the components targeting .NET Standard 2.0 and running a private NuGet feed with the resulting builds.

#### Replacing WPF

The much larger and more involved task will be to replace the WPF UI with something else. Likely a combination of a VueJS web frontend for laying out controls, with settings and status going to a GtkSharp frontend.

#### Smaller tasks

- Configuration should be moved out of the registry (XML based in the same location as logs and `Controls.xml`
- Verify `Environment.GetFolderPath` paths on systems other than Windows

#### Roadmap
- [ ] Create new project targeting .NET Standard 2.0
    - [ ] Add GtkSharp dependency with system tray icon
    - [ ] Add Suave.IO and Nancy under OWIN self-hosting
    - [ ] Add SignalR 2.X under OWIN self-hosting
- [ ] Include core classes and components that will not be replaced (`WebServer`, `Persistence`, `Web`, etc.)
- [ ] Build cross-platform UIs
    - [ ] GtkSharp status and configuration UI
    - [ ] Layout UI (GtkSharp or Web?)
